import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args:['--use-gl=swiftshader','--enable-webgl','--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport:{ width:1440, height:900 } });
await p.goto('http://localhost:4399/servicios/produccion-creativa/', { waitUntil:'networkidle' });
await p.waitForTimeout(400);
await p.$eval('.reel-gallery', el=>el.scrollIntoView());
await p.click('[data-video-toggle]');
await p.waitForTimeout(600);
await p.$eval('.phase-band', el=>el.scrollIntoView({block:'center'}));
await p.waitForTimeout(1400);
await p.click('.phase-grid .phase-card:nth-child(3)');
await p.waitForTimeout(600);
await p.screenshot({ path:'/tmp/claude-0/-home-user-Web-Page-FinalEdge-Redesign/f7589625-7599-5de6-9a12-fd16201d299a/scratchpad/band3.png' });
await b.close();
